spring.datasource:
  url: jdbc:postgresql://localhost:5432/camunda
  username: camunda
  password: camunda
camunda.bpm:
  metrics:
    enabled: true
  default-number-of-retries: 1
  authorization:
    enabled: true
  eventing:
    execution: true
    history: true
    task: true
# ONLY FOR LDAP TEST - REMOVE IF WITHOUT LDAP
  admin-user:
    id: demo
    password: demo
    firstName: Demo
    lastName: Demo
  filter:
    create: All Tasks
  job-execution:
    enabled: false
    queue-capacity: 100
    core-pool-size: 4
    max-pool-size: 10
    lock-time-in-millis: 1800000
    wait-time-in-millis: 2500
    max-jobs-per-acquisition: 50
    deployment-aware: true
  default-serialization-format: application/json
  #database:
    #schema-update: create-drop
  history-level: audit
  generic-properties:
    properties:
      historyTimeToLive: 1
server.port: 9090
management.endpoint.health.show-details: always

#logging:
  #file.path: './log'
  #level:
    #Performance logs:
    #org.camunda.bpm.engine.impl.persistence.entity.JobEntity: DEBUG
    #org.camunda.bpm.engine.jobexecutor: DEBUG
    #org.camunda.bpm.engine.impl.persistence.entity: DEBUG
    #org.camunda.bpm.engine.cmd.: DEBUG
    #root: DEBUG
    #org.camunda.bpm.engine: DEBUG
    #org.camunda.bpm.engine.impl.persistence.entity.ExternalTaskEntity: DEBUG
    #org.camunda.bpm.engine.impl.persistence.entity.SignalEventSubscriptionEntity: DEBUG
    #org.camunda.bpm.engine.impl.persistence.entity.EventSubscriptionEntity: DEBUG
    #org.camunda.bpm.engine.tx: DEBUG
    #org.camunda.bpm.sql: DEBUG
    #org.apache.ibatis.level: DEBUG
    #org.camunda.bpm.engine.pvm: DEBUG
    #org.camunda.bpm.engine.persistence: DEBUG
    #org.camunda.bpm.engine.impl.persistence.entity: DEBUG
    #org.camunda.bpm.engine.rest: DEBUG
    #org.camunda.bpm.engine.impl.history.event: DEBUG
    #org.camunda.bpm.engine.impl.batch: DEBUG
    #org.camunda.bpm.engine.impl.cmmn.entity: DEBUG
    #org.camunda.bpm.engine.impl.dmn.entity.repository: DEBUG
    #org.camunda.bpm.engine.history: DEBUG
    #org.camunda.bpm.engine.metrics: DEBUG
    #org.camunda.bpm.engine.impl.cmd.ExternalTaskCmd: DEBUG

environment.dev:
  url: http://dev.bar.com
  name: Developer Setup
  oauth: auth
  oauthsecret: secret
  oauthtoken: test
  OAuthConsumerS1: s1
  OAuthConsumerS2: s2